ONOS_IP = 'localhost'
ONOS_PORT = 8181
ONOS_USER = 'onos'
ONOS_PASS = 'rocks'

EDGE_BANDWIDTH_LIMIT = 25e3 # unit: Kbps
LINK_BANDWIDTH_LIMIT = 25e3 # unit: Kbps
BANDWIDTH_THRESHOLD = 1.0

POLLING_INTERVAL = 5
STATISTICS_INTERVAL = 4
